create table categories (age_limit integer not null, id bigint not null auto_increment, name varchar(255) not null, gender enum ('MAN','WOMAN') not null, type enum ('SINGLE') default 'SINGLE' not null, primary key (id)) engine=InnoDB;
create table confirmation_token_seq (next_val bigint) engine=InnoDB;
insert into confirmation_token_seq values ( 1 );
create table confirmation_token (created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null, user_id bigint, token varchar(255) not null, primary key (id)) engine=InnoDB;
create table event_user (event_id bigint not null, user_id bigint not null) engine=InnoDB;
create table events (date date, id bigint not null auto_increment, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table game (round integer, sets_away integer, sets_home integer, id bigint not null auto_increment, next_match_id bigint, player_away_id bigint, player_home_id bigint, player_winner_id bigint, `tournament-id` bigint, state enum ('CREATED','DONE','RUNNING','SCHEDULED','WALK_OVER'), primary key (id)) engine=InnoDB;
create table player_category (points integer default 100, category_id bigint, id bigint not null auto_increment, player_id bigint, primary key (id)) engine=InnoDB;
create table players (id bigint not null auto_increment, birthday date, firstname varchar(255), gender enum ('MAN','WOMAN'), lastname varchar(255), primary key (id)) engine=InnoDB;
create table points_away (points_away integer, points_away_id bigint not null) engine=InnoDB;
create table points_home (points_home integer, points_home_id bigint not null) engine=InnoDB;
create table refreshtoken (created_at datetime(6) not null, expires_at datetime(6) not null, expiry_date datetime(6) not null, id bigint not null, user_id bigint, token varchar(255) not null, primary key (id)) engine=InnoDB;
create table refreshtoken_seq (next_val bigint) engine=InnoDB;
insert into refreshtoken_seq values ( 1 );
create table reset_password_token (created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null, user_id bigint, token varchar(255) not null, primary key (id)) engine=InnoDB;
create table reset_password_token_seq (next_val bigint) engine=InnoDB;
insert into reset_password_token_seq values ( 1 );
create table tournament_player (player_id bigint not null, tournament_id bigint not null) engine=InnoDB;
create table tournaments (is_running bit default false, number_of_rounds integer default 0 not null, category_id bigint, event_id bigint, id bigint not null auto_increment, name varchar(255), tournament_type enum ('DOUBLE_ELIMINATION','SINGLE_ELIMINATION') default 'SINGLE_ELIMINATION', primary key (id)) engine=InnoDB;
create table users (is_active bit not null, role tinyint not null check (role between 0 and 2), created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), email varchar(100) not null, fullname varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
alter table confirmation_token add constraint UK3rtt9efhavjo2dfx9f763sypm unique (user_id);
alter table confirmation_token add constraint UK54wolcn5ryqshiq8gq0epvr3v unique (token);
alter table events add constraint UKfn2r8jg0sm5v6vhoa7yqw55vy unique (name);
alter table refreshtoken add constraint UK81otwtvdhcw7y3ipoijtlb1g3 unique (user_id);
alter table refreshtoken add constraint UKor156wbneyk8noo4jstv55ii3 unique (token);
alter table reset_password_token add constraint UK48tx38u7rrhldrpgxswjwyfhg unique (user_id);
alter table reset_password_token add constraint UKm1q62so82atxntbpu9nrwu9o0 unique (token);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table confirmation_token add constraint FKah4p1rycwibwm6s9bsyeckq51 foreign key (user_id) references users (id);
alter table event_user add constraint FK45uvxaov8fbham8l63a7jkbyr foreign key (user_id) references users (id);
alter table event_user add constraint FKdip9gnrj5k5vd2jlyjmxrnlch foreign key (event_id) references events (id);
alter table game add constraint FK4413jf3sasjw1390sk2dyumuo foreign key (player_away_id) references players (id);
alter table game add constraint FKh1boy0bgc38k16uu68mp3p0tf foreign key (player_home_id) references players (id);
alter table game add constraint FKrb1rqjxqkc0hx05umqdoimk4y foreign key (player_winner_id) references players (id);
alter table game add constraint FK2v5jwo1pnfgeehxl479l43ocs foreign key (`tournament-id`) references tournaments (id);
alter table player_category add constraint FKc6onul5c6uloavt37qyj1rr7e foreign key (category_id) references categories (id);
alter table player_category add constraint FKse39fb6jrpamt4b49291vff4k foreign key (player_id) references players (id);
alter table points_away add constraint FKaq514q4d0ligr2vccu9vtqyw3 foreign key (points_away_id) references game (id);
alter table points_home add constraint FKem4nykk17i7795347uc6e0c9p foreign key (points_home_id) references game (id);
alter table refreshtoken add constraint FKa652xrdji49m4isx38pp4p80p foreign key (user_id) references users (id);
alter table reset_password_token add constraint FKlu8wgvb3mkbxir0sls596u7np foreign key (user_id) references users (id);
alter table tournament_player add constraint FK2wp73noaodpptjeq16wiwm0xj foreign key (player_id) references players (id);
alter table tournament_player add constraint FK89rcxb6dayj98gdve7vsn1876 foreign key (tournament_id) references tournaments (id);
alter table tournaments add constraint FKsshy3kppp6u0vgn166f80cki2 foreign key (category_id) references categories (id);
alter table tournaments add constraint FKls8pk7aoublxdmcj7e8xc107t foreign key (event_id) references events (id);
