version: '3'
services:
  mysql:
    image: mysql:9.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: ttt_db
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ttt_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    

