version: '3'
services:

  mysql:
    image: mysql:9.0
    ports:
      - "3306:3306"
    env_file: ./.env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
    networks:
      - springboot-mysql-network

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - springboot-mysql-network

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network