version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file: .env.development
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 20
      timeout: 30s
    networks:
      - app-network

  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    env_file: .env.development
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080
        - VITE_WS_URL=ws://localhost:8080
    volumes:
      - ./frontend/src:/react-app/src
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: