version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file: .env.production
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 20
      timeout: 30s
    networks:
      - app-network

  backend:
    image: ghcr.io/wajhub/tournamentstabletennisweb/backend:latest
    env_file: .env.production
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: ghcr.io/wajhub/tournamentstabletennisweb/frontend:latest
    volumes:
      - ./frontend/src:/react-app/src
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-networ

volumes:
  mysql-data:
networks:
  app-network: